name: Barani App on AWS
on:
  push:
    branches:
    - main
  
jobs:
  Build-App:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  
      - name: Step 1
        run: 
         echo "We are learning about DevOps today"
      - name: Step 2
        run: 
         echo "We are learning about DevOps today"
      - name: Step 3
        run: 
         echo "We are learning about DevOps today"
      - name: Step 4
        run: 
         echo "We are learning about DevOps today"
      - name: Step 5
        run: 
         echo "We are learning about DevOps today"
      - name: Step 6
        run: 
         echo "We are learning about DevOps today"
